### Install & Import

In [5]:
!pip install numpy

In [2]:
import numpy as np

### Some basic operations

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
type(a) # type

numpy.ndarray

In [6]:
a.shape

(4,)

In [7]:
a.ndim

1

In [8]:
a.size

4

In [9]:
a[0]

1

In [10]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [11]:
b.shape

(3, 3)

In [12]:
b.ndim

2

In [13]:
b.size

9

In [14]:
b[0][0]

1

### Operations

In [15]:
b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [16]:
b ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [17]:
b + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Creating Arrays

In [18]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [19]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

In [24]:
np.eye(2) # identity matrix

array([[1., 0.],
       [0., 1.]])

In [26]:
np.random.random((2, 2))

array([[0.12360327, 0.80622316],
       [0.75362681, 0.66447974]])

### Indexing

In [31]:
a = np.random.random((10, 10))

In [32]:
a

array([[0.82303057, 0.85801998, 0.33416872, 0.18690237, 0.56316706,
        0.20035453, 0.60873281, 0.85499206, 0.80799148, 0.05171588],
       [0.60064859, 0.71267976, 0.763865  , 0.36295405, 0.57842532,
        0.59346505, 0.04699044, 0.84279053, 0.43969875, 0.19771574],
       [0.1491921 , 0.00932871, 0.90170386, 0.58450644, 0.70659927,
        0.49540684, 0.80910091, 0.73436504, 0.27553451, 0.39200886],
       [0.11718727, 0.94473279, 0.40581787, 0.41386498, 0.12953138,
        0.43301617, 0.33568416, 0.32394764, 0.27710599, 0.67951312],
       [0.26922596, 0.45198299, 0.45932088, 0.33525903, 0.1433297 ,
        0.716727  , 0.25372186, 0.60509366, 0.70982519, 0.55602132],
       [0.89746801, 0.90757278, 0.76790477, 0.22796796, 0.1841017 ,
        0.27009819, 0.10954467, 0.74014424, 0.21939248, 0.27147083],
       [0.79259204, 0.59635829, 0.05662406, 0.85183469, 0.05788413,
        0.23010343, 0.10396052, 0.96602896, 0.52654404, 0.23115264],
       [0.00733352, 0.03411038, 0.7820648

In [33]:
a[0][0]

0.8230305665414188

In [34]:
a[1, :]

array([0.60064859, 0.71267976, 0.763865  , 0.36295405, 0.57842532,
       0.59346505, 0.04699044, 0.84279053, 0.43969875, 0.19771574])

In [36]:
a[:, 1]

array([0.85801998, 0.71267976, 0.00932871, 0.94473279, 0.45198299,
       0.90757278, 0.59635829, 0.03411038, 0.65404785, 0.94124287])

In [37]:
a[1:5, 1]

array([0.71267976, 0.00932871, 0.94473279, 0.45198299])

In [38]:
a[1:5, 1:5]

array([[0.71267976, 0.763865  , 0.36295405, 0.57842532],
       [0.00932871, 0.90170386, 0.58450644, 0.70659927],
       [0.94473279, 0.40581787, 0.41386498, 0.12953138],
       [0.45198299, 0.45932088, 0.33525903, 0.1433297 ]])

In [40]:
a[a > 0.5]

array([0.82303057, 0.85801998, 0.56316706, 0.60873281, 0.85499206,
       0.80799148, 0.60064859, 0.71267976, 0.763865  , 0.57842532,
       0.59346505, 0.84279053, 0.90170386, 0.58450644, 0.70659927,
       0.80910091, 0.73436504, 0.94473279, 0.67951312, 0.716727  ,
       0.60509366, 0.70982519, 0.55602132, 0.89746801, 0.90757278,
       0.76790477, 0.74014424, 0.79259204, 0.59635829, 0.85183469,
       0.96602896, 0.52654404, 0.78206481, 0.87360183, 0.75313432,
       0.79444934, 0.89102508, 0.55090233, 0.87728092, 0.65404785,
       0.55247706, 0.79569457, 0.63841179, 0.70001792, 0.94124287,
       0.59775401, 0.84575312])

### Change Datatype

In [42]:
a.astype(np.int_)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Array Operations

In [43]:
a

array([[0.82303057, 0.85801998, 0.33416872, 0.18690237, 0.56316706,
        0.20035453, 0.60873281, 0.85499206, 0.80799148, 0.05171588],
       [0.60064859, 0.71267976, 0.763865  , 0.36295405, 0.57842532,
        0.59346505, 0.04699044, 0.84279053, 0.43969875, 0.19771574],
       [0.1491921 , 0.00932871, 0.90170386, 0.58450644, 0.70659927,
        0.49540684, 0.80910091, 0.73436504, 0.27553451, 0.39200886],
       [0.11718727, 0.94473279, 0.40581787, 0.41386498, 0.12953138,
        0.43301617, 0.33568416, 0.32394764, 0.27710599, 0.67951312],
       [0.26922596, 0.45198299, 0.45932088, 0.33525903, 0.1433297 ,
        0.716727  , 0.25372186, 0.60509366, 0.70982519, 0.55602132],
       [0.89746801, 0.90757278, 0.76790477, 0.22796796, 0.1841017 ,
        0.27009819, 0.10954467, 0.74014424, 0.21939248, 0.27147083],
       [0.79259204, 0.59635829, 0.05662406, 0.85183469, 0.05788413,
        0.23010343, 0.10396052, 0.96602896, 0.52654404, 0.23115264],
       [0.00733352, 0.03411038, 0.7820648

In [44]:
b = np.random.random((10, 10))

In [45]:
b

array([[0.96724439, 0.17722653, 0.88966831, 0.49641383, 0.1057747 ,
        0.84223871, 0.70110126, 0.84534287, 0.6042989 , 0.09917873],
       [0.18230306, 0.25722806, 0.88744574, 0.22291007, 0.03945645,
        0.81718516, 0.82938577, 0.75911908, 0.48091669, 0.69647469],
       [0.40316711, 0.15327174, 0.00809929, 0.48016052, 0.8273781 ,
        0.54080829, 0.88673487, 0.41609042, 0.5289115 , 0.45432369],
       [0.51401872, 0.03460435, 0.38094155, 0.49276841, 0.77394143,
        0.69073545, 0.94051217, 0.52974964, 0.15632543, 0.96085148],
       [0.8855036 , 0.14684633, 0.83937   , 0.7970088 , 0.12435673,
        0.65671729, 0.95706456, 0.11631344, 0.07794535, 0.46440937],
       [0.54211577, 0.56878667, 0.3326034 , 0.50279504, 0.77371408,
        0.36455399, 0.17459109, 0.87997759, 0.31009125, 0.2673235 ],
       [0.47559131, 0.00768391, 0.16258989, 0.28019467, 0.48933218,
        0.31928272, 0.41216025, 0.1628813 , 0.6460437 , 0.45069004],
       [0.47086907, 0.65627781, 0.7916443

In [46]:
a + b

array([[1.79027496, 1.03524651, 1.22383703, 0.68331621, 0.66894177,
        1.04259324, 1.30983406, 1.70033493, 1.41229038, 0.15089461],
       [0.78295164, 0.96990782, 1.65131075, 0.58586412, 0.61788177,
        1.41065021, 0.87637621, 1.60190961, 0.92061544, 0.89419043],
       [0.5523592 , 0.16260045, 0.90980315, 1.06466697, 1.53397738,
        1.03621513, 1.69583578, 1.15045545, 0.80444601, 0.84633255],
       [0.63120599, 0.97933714, 0.78675942, 0.90663339, 0.90347281,
        1.12375162, 1.27619633, 0.85369727, 0.43343142, 1.6403646 ],
       [1.15472955, 0.59882932, 1.29869088, 1.13226783, 0.26768643,
        1.37344429, 1.21078641, 0.72140711, 0.78777054, 1.02043069],
       [1.43958378, 1.47635945, 1.10050818, 0.730763  , 0.95781578,
        0.63465218, 0.28413576, 1.62012183, 0.52948373, 0.53879433],
       [1.26818335, 0.6040422 , 0.21921395, 1.13202936, 0.54721631,
        0.54938615, 0.51612077, 1.12891026, 1.17258773, 0.68184268],
       [0.47820259, 0.69038818, 1.5737091

In [47]:
a - b

array([[-0.14421382,  0.68079345, -0.55549958, -0.30951146,  0.45739236,
        -0.64188418, -0.09236845,  0.0096492 ,  0.20369258, -0.04746285],
       [ 0.41834553,  0.4554517 , -0.12358074,  0.14004399,  0.53896888,
        -0.22372011, -0.78239533,  0.08367145, -0.04121795, -0.49875895],
       [-0.25397501, -0.14394303,  0.89360457,  0.10434592, -0.12077883,
        -0.04540145, -0.07763395,  0.31827462, -0.25337699, -0.06231483],
       [-0.39683145,  0.91012844,  0.02487632, -0.07890343, -0.64441004,
        -0.25771928, -0.60482801, -0.205802  ,  0.12078056, -0.28133835],
       [-0.61627764,  0.30513666, -0.38004912, -0.46174977,  0.01897297,
         0.06000971, -0.7033427 ,  0.48878022,  0.63187984,  0.09161195],
       [ 0.35535224,  0.33878612,  0.43530137, -0.27482708, -0.58961238,
        -0.09445579, -0.06504642, -0.13983336, -0.09069877,  0.00414733],
       [ 0.31700073,  0.58867438, -0.10596583,  0.57164002, -0.43144805,
        -0.08917929, -0.30819973,  0.80314766

In [48]:
a * b

array([[0.7960717 , 0.15206391, 0.29729932, 0.09278092, 0.05956883,
        0.16874634, 0.42678333, 0.72276144, 0.48826836, 0.00512912],
       [0.10950007, 0.18332123, 0.67788875, 0.08090611, 0.02282261,
        0.48497083, 0.0389732 , 0.63977837, 0.21145847, 0.13770401],
       [0.06014935, 0.00142983, 0.00730316, 0.28065692, 0.58462477,
        0.26792013, 0.71745799, 0.30556225, 0.14573337, 0.17809891],
       [0.06023645, 0.03269187, 0.15459289, 0.20393959, 0.1002497 ,
        0.29909962, 0.31571504, 0.17161114, 0.04331871, 0.65291119],
       [0.23840055, 0.06637204, 0.38554017, 0.2672044 , 0.01782401,
        0.47068701, 0.24282819, 0.07038053, 0.05532757, 0.25822151],
       [0.48653156, 0.5162153 , 0.25540774, 0.11462116, 0.14244208,
        0.09846537, 0.01912552, 0.65131034, 0.06803169, 0.07257053],
       [0.37694988, 0.00458236, 0.0092065 , 0.23867954, 0.02832457,
        0.07346805, 0.04284839, 0.15734805, 0.34017045, 0.10417819],
       [0.00345313, 0.02238588, 0.6191171

In [49]:
a / b

array([[8.50902393e-01, 4.84137430e+00, 3.75610462e-01, 3.76505167e-01,
        5.32421314e+00, 2.37883307e-01, 8.68252341e-01, 1.01141454e+00,
        1.33707256e+00, 5.21441248e-01],
       [3.29478067e+00, 2.77061437e+00, 8.60745583e-01, 1.62825330e+00,
        1.46598433e+01, 7.26230817e-01, 5.66569195e-02, 1.11022177e+00,
        9.14292962e-01, 2.83880726e-01],
       [3.70050265e-01, 6.08638601e-02, 1.11331210e+02, 1.21731466e+00,
        8.54022206e-01, 9.16048898e-01, 9.12449643e-01, 1.76491697e+00,
        5.20946341e-01, 8.62840449e-01],
       [2.27982496e-01, 2.73009825e+01, 1.06530219e+00, 8.39877252e-01,
        1.67365876e-01, 6.26891487e-01, 3.56916339e-01, 6.11510821e-01,
        1.77262263e+00, 7.07198916e-01],
       [3.04037111e-01, 3.07793180e+00, 5.47220988e-01, 4.20646583e-01,
        1.15256889e+00, 1.09137831e+00, 2.65104223e-01, 5.20226769e+00,
        9.10670389e+00, 1.19726550e+00],
       [1.65549142e+00, 1.59562950e+00, 2.30877003e+00, 4.53401367e-01,
   

In [50]:
np.dot(a, b)

array([[3.17619933, 1.74825351, 3.14465584, 2.02106498, 1.74746485,
        2.86158392, 2.85381238, 2.64513358, 2.83309249, 2.47011263],
       [2.95949193, 1.83414517, 2.96991308, 2.20288646, 2.11036562,
        2.90040652, 3.06245802, 2.57310387, 2.48212024, 2.56503944],
       [2.94410121, 1.5465144 , 2.28068543, 2.34498353, 2.63477847,
        2.45276337, 3.05933069, 1.74842225, 2.41818523, 2.65061138],
       [2.0435543 , 1.53315604, 2.37521507, 1.77062846, 1.87199615,
        2.10905614, 2.67034143, 1.92242437, 2.15841976, 2.19343583],
       [2.60263101, 1.96810133, 2.35794344, 1.95063147, 2.26972936,
        2.03468016, 2.34905469, 2.266377  , 2.47328169, 2.11061366],
       [2.54621936, 1.54000596, 2.85655958, 1.83434536, 1.67407839,
        2.81600055, 2.9273509 , 2.39560197, 2.47408939, 2.27185623],
       [2.61215059, 1.62721364, 2.82118442, 1.66645607, 1.69818376,
        2.54700853, 2.45420873, 2.32057134, 2.3032094 , 2.47034796],
       [3.08799699, 1.6403041 , 2.3485521